Traceback (most recent call last):
  File "/Users/juliehartley/Library/Python/3.9/lib/python/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/juliehartley/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/juliehartley/Library/Python/3.9/lib/python/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/juliehartley/Library/Python/3.9/lib/python/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/juliehartley/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/juliehartley/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/juliehartley/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib.pyplot as plt
import numpy as np

x = x = np.linspace(-10, 10, 100)
zero_line = np.zeros(len(x))

sigma = 1/(1 + np.exp(-x))
tanh = (np.exp(x) - np.exp(-x))/(np.exp(x) + np.exp(-x))
plt.plot(x, y) 
plt.plot(x, zero_line, color='black')
plt.ylabel('sigmoid (x)')
plt.grid()

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn [1], line 9[0m
[1;32m      7[0m sigma [38;5;241m=[39m [38;5;241m1[39m[38;5;241m/[39m([38;5;241m1[39m [38;5;241m+[39m np[38;5;241m.[39mexp([38;5;241m-[39mx))
[1;32m      8[0m tanh [38;5;241m=[39m (np[38;5;241m.[39mexp(x) [38;5;241m-[39m np[38;5;241m.[39mexp([38;5;241m-[39mx))[38;5;241m/[39m(np[38;5;241m.[39mexp(x) [38;5;241m+[39m np[38;5;241m.[39mexp([38;5;241m-[39mx))
[0;32m----> 9[0m plt[38;5;241m.[39mplot(x, [43my[49m) 
[1;32m     10[0m plt[38;5;241m.[39mplot(x, zero_line, color[38;5;241m=[39m[38;5;124m'[39m[38;5;124mblack[39m[38;5;124m'[39m)
[1;32m     11[0m plt[38;5;241m.[39mylabel([38;5;124m'[39m[38;5;124msigmoid (x)[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'y' is not defined
NameError: name 'y' is not defined

